import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import Nav from "@/components/shared/Navbar/Nav";
import { Container } from "@mui/material";
import Header from "@/components/shared/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar/>

        <Container className="min-h-screen" >{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
